name: Test Validator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Validator Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache-dependency-path: 'go.sum'

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests with race detection
        run: go test -race -v ./...

      - name: Run benchmarks
        run: go test -bench=. -benchmem ./...

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out -covermode=atomic $(go list ./... | grep -vE "/cdp")

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          slug: display-protocol/dp1-validator
          flags: validator
          name: dp1-validator-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Build project
        run: go build -v ./...
